
name: Build CasProcessor

# 手動実行
on:
  workflow_dispatch:

# ジョブの定義
jobs:

  build:
    runs-on: windows-2019
    steps:

      # MSBuild のセットアップ
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      # TvCas (B25.tvcas / B1.tvcas) のビルド
      - name: Build TvCas (B25.tvcas / B1.tvcas)
        run: |
          git clone -b master https://github.com/tsukumijima/TvCas.git
          cd TvCas/
          msbuild TvCas.sln /t:Build /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142
          cp -Path x64/Release/B1.tvcas -Destination ../
          cp -Path x64/Release/B25.tvcas -Destination ../

      # CasProcessor のビルド
      - name: Build CasProcessor
        run: |
          git clone -b master https://github.com/tsukumijima/CasProcessor.git
          cd CasProcessor/
          msbuild CasProcessor.sln /t:Build /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142
          mkdir ../Plugins
          cp -Path x64/Release/CasProcessor.tvtp -Destination ../Plugins

      # Artifact としてアップロード
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CasProcessor-and-TvCas.zip
          path: |
            B1.tvcas
            B25.tvcas
            Plugins/CasProcessor.tvtp
